export const UPDATE_DOUBTS="UPDATE_DOUBTS";
export const ACCEPT_DOUBT="ACCEPT_DOUBT";
export const RESOLVE_DOUBT="RESOLVE_DOUBT";
export const SEARCH_DOUBT="SEARCH_DOUBT";
export const UPDATE_ACTIVE_DOUBT="UPDATE_ACTIVE_DOUBT";
export const UPDATE_RESOLVED_DOUBT="UPDATE_RESOLVED_DOUBT"


